; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -S | FileCheck %s
; RUN: llvm-as < %s | opt -S | FileCheck %s

define void @test_ptrauth_sign(i64 %p, i64 %addr) {
; CHECK-LABEL: @test_ptrauth_sign(
; CHECK-NEXT:    [[ZERO_DISCR:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[P:%.*]]) [ "ptrauth"(i64 1, i64 0, i64 0) ]
; CHECK-NEXT:    [[IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[P]]) [ "ptrauth"(i64 1, i64 42, i64 0) ]
; CHECK-NEXT:    [[ADDR_DISCR:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[P]]) [ "ptrauth"(i64 1, i64 0, i64 [[ADDR:%.*]]) ]
; CHECK-NEXT:    [[BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[P]]) [ "ptrauth"(i64 1, i64 1234, i64 [[ADDR]]) ]
; CHECK-NEXT:    ret void
;
  %tmp = call i64 @llvm.ptrauth.blend(i64 %addr, i64 1234)
  %zero.discr    = call i64 @llvm.ptrauth.sign(i64 %p, i32 1, i64 0)
  %imm.discr     = call i64 @llvm.ptrauth.sign(i64 %p, i32 1, i64 42)
  %addr.discr    = call i64 @llvm.ptrauth.sign(i64 %p, i32 1, i64 %addr)
  %blended.discr = call i64 @llvm.ptrauth.sign(i64 %p, i32 1, i64 %tmp)
  ret void
}

define void @test_ptrauth_auth(i64 %p, i64 %addr) {
; CHECK-LABEL: @test_ptrauth_auth(
; CHECK-NEXT:    [[ZERO_DISCR:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P:%.*]]) [ "ptrauth"(i64 1, i64 0, i64 0) ]
; CHECK-NEXT:    [[IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P]]) [ "ptrauth"(i64 1, i64 42, i64 0) ]
; CHECK-NEXT:    [[ADDR_DISCR:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P]]) [ "ptrauth"(i64 1, i64 0, i64 [[ADDR:%.*]]) ]
; CHECK-NEXT:    [[BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P]]) [ "ptrauth"(i64 1, i64 1234, i64 [[ADDR]]) ]
; CHECK-NEXT:    ret void
;
  %tmp = call i64 @llvm.ptrauth.blend(i64 %addr, i64 1234)
  %zero.discr    = call i64 @llvm.ptrauth.auth(i64 %p, i32 1, i64 0)
  %imm.discr     = call i64 @llvm.ptrauth.auth(i64 %p, i32 1, i64 42)
  %addr.discr    = call i64 @llvm.ptrauth.auth(i64 %p, i32 1, i64 %addr)
  %blended.discr = call i64 @llvm.ptrauth.auth(i64 %p, i32 1, i64 %tmp)
  ret void
}

define void @test_ptrauth_resign(i64 %p, i64 %addr) {
; CHECK-LABEL: @test_ptrauth_resign(
; CHECK-NEXT:    [[IMM_IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P:%.*]]) [ "ptrauth"(i64 1, i64 42, i64 0), "ptrauth"(i64 2, i64 123, i64 0) ]
; CHECK-NEXT:    [[ZERO_IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 0, i64 0), "ptrauth"(i64 2, i64 123, i64 0) ]
; CHECK-NEXT:    [[ADDR_IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 0, i64 [[ADDR:%.*]]), "ptrauth"(i64 2, i64 123, i64 0) ]
; CHECK-NEXT:    [[BLENDED_IMM_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 1234, i64 [[ADDR]]), "ptrauth"(i64 2, i64 123, i64 0) ]
; CHECK-NEXT:    [[IMM_ZERO_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 123, i64 0), "ptrauth"(i64 2, i64 0, i64 0) ]
; CHECK-NEXT:    [[IMM_ADDR_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 123, i64 0), "ptrauth"(i64 2, i64 0, i64 [[ADDR]]) ]
; CHECK-NEXT:    [[IMM_BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 123, i64 0), "ptrauth"(i64 2, i64 5678, i64 [[ADDR]]) ]
; CHECK-NEXT:    [[ZERO_BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 0, i64 0), "ptrauth"(i64 2, i64 4321, i64 [[ADDR]]) ]
; CHECK-NEXT:    [[ADDR_BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 0, i64 [[ADDR]]), "ptrauth"(i64 2, i64 4321, i64 [[ADDR]]) ]
; CHECK-NEXT:    [[BLENDED_ZERO_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 8765, i64 [[ADDR]]), "ptrauth"(i64 2, i64 0, i64 0) ]
; CHECK-NEXT:    [[BLENDED_ADDR_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 8765, i64 [[ADDR]]), "ptrauth"(i64 2, i64 0, i64 [[ADDR]]) ]
; CHECK-NEXT:    [[BLENDED_BLENDED_DISCR:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P]]) [ "ptrauth"(i64 1, i64 111, i64 [[ADDR]]), "ptrauth"(i64 2, i64 222, i64 [[ADDR]]) ]
; CHECK-NEXT:    ret void
;
  %imm.imm.discr     = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 42,    i32 2, i64 123)

  %tmp1 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 1234)
  %zero.imm.discr    = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 0,     i32 2, i64 123)
  %addr.imm.discr    = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 %addr, i32 2, i64 123)
  %blended.imm.discr = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 %tmp1, i32 2, i64 123)

  %tmp2 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 5678)
  %imm.zero.discr    = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 123, i32 2, i64 0    )
  %imm.addr.discr    = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 123, i32 2, i64 %addr)
  %imm.blended.discr = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 123, i32 2, i64 %tmp2)

  %tmp3 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 4321)
  %zero.blended.discr    = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 0,     i32 2, i64 %tmp3)
  %addr.blended.discr    = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 %addr, i32 2, i64 %tmp3)

  %tmp4 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 8765)
  %blended.zero.discr    = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 %tmp4, i32 2, i64 0    )
  %blended.addr.discr    = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 %tmp4, i32 2, i64 %addr)

  %tmp5 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 111)
  %tmp6 = call i64 @llvm.ptrauth.blend(i64 %addr, i64 222)
  %blended.blended.discr = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 %tmp5,  i32 2, i64 %tmp6)

  ret void
}

define void @test_ptrauth_strip(i64 %p) {
; CHECK-LABEL: @test_ptrauth_strip(
; CHECK-NEXT:    [[RES:%.*]] = call i64 @llvm.ptrauth.strip(i64 [[P:%.*]]) [ "ptrauth"(i64 1) ]
; CHECK-NEXT:    ret void
;
  %res = call i64 @llvm.ptrauth.strip(i64 %p, i32 1)
  ret void
}

define void @test_ptrauth_reused_blend(i64 %p1, i64 %p2, i64 %addr) {
; CHECK-LABEL: @test_ptrauth_reused_blend(
; CHECK-NEXT:    [[RES1:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P1:%.*]]) [ "ptrauth"(i64 1, i64 1234, i64 [[ADDR:%.*]]) ]
; CHECK-NEXT:    [[RES2:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[P2:%.*]]) [ "ptrauth"(i64 2, i64 1234, i64 [[ADDR]]) ]
; CHECK-NEXT:    ret void
;
  %tmp = call i64 @llvm.ptrauth.blend(i64 %addr, i64 1234)
  %res1 = call i64 @llvm.ptrauth.auth(i64 %p1, i32 1, i64 %tmp)
  %res2 = call i64 @llvm.ptrauth.auth(i64 %p2, i32 2, i64 %tmp)
  ret void
}

define void @test_ptrauth_reused_blend_same_inst(i64 %p, i64 %addr) {
; CHECK-LABEL: @test_ptrauth_reused_blend_same_inst(
; CHECK-NEXT:    [[RES:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P:%.*]]) [ "ptrauth"(i64 1, i64 1234, i64 [[ADDR:%.*]]), "ptrauth"(i64 2, i64 1234, i64 [[ADDR]]) ]
; CHECK-NEXT:    ret void
;
  %tmp = call i64 @llvm.ptrauth.blend(i64 %addr, i64 1234)
  %res = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 %tmp, i32 2, i64 %tmp)
  ret void
}

define void @test_ptrauth_blend_in_other_bb(i64 %p, i64 %addr) {
; CHECK-LABEL: @test_ptrauth_blend_in_other_bb(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    [[RES:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[P:%.*]]) [ "ptrauth"(i64 1, i64 1234, i64 [[ADDR:%.*]]), "ptrauth"(i64 2, i64 1234, i64 [[ADDR]]) ]
; CHECK-NEXT:    ret void
;
entry:
  %tmp = call i64 @llvm.ptrauth.blend(i64 %addr, i64 1234)
  br label %exit

exit:
  %res = call i64 @llvm.ptrauth.resign(i64 %p, i32 1, i64 %tmp, i32 2, i64 %tmp)
  ret void
}

define i64 @test_unused_blend(i64 %addr) {
; CHECK-LABEL: @test_unused_blend(
; CHECK-NEXT:    ret i64 [[ADDR:%.*]]
;
  %tmp = call i64 @llvm.ptrauth.blend(i64 %addr, i64 1234)
  ret i64 %addr
}
